# Generated by Django 4.2 on 2024-08-30 21:49

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='posts/images/', verbose_name='Image')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('tools', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='posts/images/', verbose_name='Image')),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('type', models.CharField(choices=[('escritos', 'Escritos'), ('recomendaciones', 'Recomendaciones')], max_length=15)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('categories', models.ManyToManyField(related_name='posts', to='category.categories')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
