# Generated by Django 4.2 on 2024-09-06 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=datetime.date.today),
        ),
    ]
