# Generated by Django 4.2 on 2024-09-06 19:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_art_date_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='date',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name=datetime.date.today),
        ),
    ]
